docker:
  image: yegor256/rultor-image:1.22.0
assets:
  docker-password: h1alexbel/home#assets/docker-password
merge:
  script: |-
    sudo docker build "$(pwd)"
release:
  pre: false
  script: |-
    [[ "${tag}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || exit -1
    repo=h1alexbel/rultor-rust-image
    sed -i -e "s/^0.0.0/${tag}/" Dockerfile
    sudo docker build "$(pwd)" --tag "${repo}:${tag}"
    sudo docker tag "${repo}:${tag}" "${repo}:latest"
    cat ../docker-password | sudo docker login --password-stdin --username h1alexbel
    sudo docker push "${repo}:${tag}"
    sudo docker push "${repo}:latest"
